<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P5-GKR0N62" name="Test-Regression" tests="4" failures="2" timestamp="14 Jun 2019 06:00:10 GMT" time="0.115" errors="0">
  <testcase name="test1" time="0.027" classname="TestngFeatures.DemoAssertion"/>
  <testcase name="test2" time="0.004" classname="TestngFeatures.DemoAssertion">
    <failure type="java.lang.AssertionError" message="Error from test2-18 greater than 20 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error from test2-18 greater than 20 expected [true] but found [false]
	at TestngFeatures.DemoAssertion.test2(DemoAssertion.java:19)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.005" classname="TestngFeatures.DemoAssertion">
    <failure type="java.lang.AssertionError" message="Error from -both values are different expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error from -both values are different expected [true] but found [false]
	at TestngFeatures.DemoAssertion.test3(DemoAssertion.java:27)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.003" classname="TestngFeatures.DemoAssertion"/>
</testsuite> <!-- Test-Regression -->
